apiVersion: v1
kind: Service
metadata:
  name: svc-go-app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001  # Port on each node
    targetPort: 3333
